[features]
resolution = true
skip-lint = false

[programs.devnet]
solvency_vault = "J2Tqd685N3uV3ViePqNS6MHA4aJa6E7gdCfS9Mv89csh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/vault"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
